### ISSUE TITLE
WPM value of  -1 issue

### ISSUE THREAD

**Issue by RytasV** [elvinukas/Typeracer#13]
Need to assign a different value to CurrentWordsPerMinute when a word was written instantly because wpm = -1 distorts the graph. Possible solution would be to use CurrentWordsPerMinute of the previous word.

**Comment by elvinukas** [comment]
<img width="1276" alt="image" src="https://github.com/user-attachments/assets/b863ccb6-b313-4d48-9c2c-68d996b165c2">
Most likely @RytasV is mentioning the dips in the graph. Yeah, most likely the 2 ways of solving this: trying to calcuate wpm with even more precision (but that could lead to extreme distortions too, like an incredibly high wpm), or, as Rytis mentioned, maintaining the same CurrentWordsPerMinute.
