### ISSUE TITLE
Last characters being typed incorrectly

### ISSUE THREAD

**Issue by RytasV** [elvinukas/Typeracer#14]
1) Needs fixing. If the last or several last characters are typed incorrectly (when typed letters are not the same as text letters), method fails to send statistics. Page still changes and data from last correct game is shown.

2) If second (or third, or fourth...) character from the end is typed incorrectly, it becomes red along with all characters (even if correctly typed) following it. And if the last character is typed correctly, method succeeds in sending statistics. In data page, it is shown that one mistake was made. Are we satisfied with it or should the user enter the last character as correct and not red?

**Comment by UPovilas** [comment]
Fixed the last character error. What to do if the user types incorrectly 19 more characters after the last one: should the user use backspace once or twenty times (if the user typed 20 unnecessary characters) to fix the error?

**Comment by RytasV** [comment]
I suggest that the user should backspace twenty times in such case.
